/*  sclc.h auto generated by mini.py  */

/* clang-format off */

#ifndef MINI_GENERATED
#define MINI_GENERATED
#endif

/*
  Copyright (c) 2026 Merian

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/


/* sclc_base.h
 * base definitions
 */

#ifndef sclc_base_h
#define sclc_base_h

#include <stdint.h>
#include <stddef.h>
#ifndef __cplusplus
#  include <stdbool.h>
#endif

#if defined(_MSC_VER)
#  include <BaseTsd.h>
#  include <malloc.h>
typedef SSIZE_T ssize_t;
#else
#  include <alloca.h>
#endif

#ifndef SCLAPI
#  if defined(_MSC_VER)
#    ifdef SCL_DLL
#      define SCLAPI __declspec(dllexport)
#    else
#      define SCLAPI
#    endif
#  else
#    ifdef SCL_DLL
#      define SCLAPI __attribute__((visibility("default")))
#    else
#      define SCLAPI
#    endif

#  endif
#endif


#endif


/*
  Copyright (c) 2026 Merian

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/


/* sclc_path.h
 *
 */

#ifndef sclc_path_h
#define sclc_path_h

#ifdef __cplusplus
extern "C" {
#endif

/*#include "sclc_base.h"*/
#include <stdio.h>

#ifdef _WIN32
#  define PATH_MAX 260
#  define _SLASH   "\\"
#else
#  include <limits.h>
#  define _SLASH "/"
#endif

#define SCL_PATH_FILES  0
#define SCL_PATH_DIRS   1

#define scl_iswild(str) (strstr(str, "*") != NULL)

extern SCLAPI int scl_pathjoinx(char* buf, const char* one, const char* two);

#define scl_pathjoin(buf, one, two)                          \
  {                                                          \
    if(!(buf))                                               \
      (buf) = alloca(scl_pathjoinx(NULL, (one), (two)) + 1); \
    scl_pathjoinx((char*)(buf), (one), (two));               \
  }

extern SCLAPI const char* scl_pathabs(const char* path, char* resolved);

extern SCLAPI const char* scl_execdir();

extern SCLAPI bool scl_pathexists(const char* path);

extern SCLAPI bool scl_isdirectory(const char* path);

extern SCLAPI bool scl_isfile(const char* path);

extern SCLAPI const char* scl_filename(const char* path);

extern SCLAPI const char* scl_pathstem(const char* path);

extern SCLAPI const char* scl_parentpath(const char* path);

extern SCLAPI const char* scl_pathcomponent(const char** path);

extern SCLAPI bool scl_chdir(const char* path);

extern SCLAPI bool scl_mkdir(const char* path);

extern SCLAPI bool scl_mkdirs(const char** paths, int count);

extern SCLAPI const char** scl_glob(
  const char* pattern, const char** finds, int mode);

extern SCLAPI int64_t scl_wtime(const char* path);

#ifdef __cplusplus
}
#endif
#endif


/*
  Copyright (c) 2026 Merian

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/


/* sclc_string.h
 * extends the existing string.h helpers
 */

#ifndef sclc_string_h
#define sclc_string_h

#ifdef __cplusplus
extern "C" {
#endif

/*#include "sclc_base.h"*/
#include <stdio.h>
#include <stdlib.h>

/**
 * @brief Finds the last instance of needle in haystack.
 *
 * @param  haystack
 * @param  needle
 * @return Returns a pointer to the last instance of needle in haystack, the
 * pointer will be in haystack, or null if no instance was found.
 */
extern SCLAPI const char* strrstr(const char* haystack, const char* needle);

/**
 * @return Returns true if end is at the end of string.
 */
extern SCLAPI bool strendswith(const char* str, const char* end);

extern SCLAPI bool strmatch(const char* str, const char* pattern);

extern SCLAPI const char* strsub(const char* str, size_t i, size_t j);

extern SCLAPI const char* strcopy(const char* str);

extern SCLAPI const char* strreplace(
  const char* str, const char* replacement, size_t i, size_t j);

extern SCLAPI const char* strreplacestr(
  const char* str, const char* pattern, const char* replacement);

/**
 * @brief Replaces any ascii lowercase letters with their uppercase varients.
 * Modifies the input string.
 *
 * @param  str
 * @return Returns the string pointer given.
 */
extern SCLAPI const char* strupper(char* str);

/**
 * @brief Replaces any ascii uppercase letters with their lowercase varients.
 * Modifies the input string.
 *
 * @param  str
 * @return Returns the string pointer given.
 */
extern SCLAPI const char* strlower(char* str);

extern SCLAPI const char* strrand(int len);

#define scl_stkfmt(buf, mx, fmt, ...)                                \
  {                                                                  \
    int __l = min(snprintf(NULL, 0, fmt, __VA_ARGS__), (int)mx - 1); \
    if(!(buf))                                                       \
      (buf) = alloca(__l + 1);                                       \
    snprintf((void*)buf, __l + 1, fmt, __VA_ARGS__);                 \
    ((char*)(buf))[__l] = 0;                                         \
  }

#define scl_stkfmtx(buf, mx, fmt, ...)                               \
  {                                                                  \
    int __l = min(snprintf(NULL, 0, fmt, __VA_ARGS__), (int)mx - 1); \
    snprintf((void*)buf, __l + 1, fmt, __VA_ARGS__);                 \
    ((char*)(buf))[__l] = 0;                                         \
  }

typedef struct strvec_header_t {
  uint32_t size;         /* Buffer size */
  const char** sentinel; /* Array sentinel pointer */
  char* strings;         /* String section start */
} strvec_header_t;

#define _svheader(vec)                                            \
  (vec ? (strvec_header_t*)((char*)vec - sizeof(strvec_header_t)) \
       : (strvec_header_t*)NULL)

extern SCLAPI const char** _svnalloc(const char** vec, int align, int bytes);

extern SCLAPI void _svappend(const char** vec, const char* str);

#define scl_svappend(vec, str, align)                   \
  {                                                     \
    (vec) = _svnalloc((vec), (align), strlen(str) + 1); \
    _svappend((vec), (str));                            \
  }

extern SCLAPI size_t _svlen(const char** vec);
#define scl_svlen(vec) _svlen(vec)

#define scl_svback(vec) \
  ((vec) ? ((const char**)(vec))[scl_svlen(vec) - 1] : NULL)

#define scl_svstrings(vec) ((vec) ? _svheader(vec)->strings : NULL)

extern SCLAPI void scl_svseparator(
  const char** vec, char oldSeparator, char separator);

#define scl_svfree(vec) \
  if(vec)               \
  free(_svheader(vec))
#ifdef __cplusplus
}
#endif
#endif


/*
  Copyright (c) 2026 Merian

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/

/* sclc_time.h
 *
 */

#ifndef sclc_time_h
#define sclc_time_h

#ifdef __cplusplus
extern "C" {
#endif

/*#include "sclc_base.h"*/

/**
 * @brief Resets the output of sclc_clock(), making current time epoch.
 *
 */
extern SCLAPI void scl_resetclock();

/**
 * @note You can use scl_resetclock() to control this function's epoch.
 *
 * @return   Seconds since epoch.
 */
extern SCLAPI double scl_clock();

/**
 * @brief Makes this thread sleep for a given amount of milliseconds.
 *
 * @param sleemms  Number of milliseconds to sleep for.
 */
extern SCLAPI void scl_waitms(double ms);

#ifdef __cplusplus
}
#endif
#endif


#undef MINI_GENERATED
/* clang-format on */
